### ISSUE TITLE
Scale down the icon to match with the dashicons

### ISSUE THREAD

**Issue by tdwesten** [ptrkcsk/fa-wp-admin-menu-icons#3] opened 2018-03-06 19:58 UTC
Hi, 

I think ik would be great to scale down the FA icon to 15px instead of 20px.
Before:
![schermafdruk 2018-03-06 20 57 36](https://user-images.githubusercontent.com/224501/37055066-0413e580-2181-11e8-904d-705051d3daae.png)
After:
![schermafdruk 2018-03-06 20 58 16](https://user-images.githubusercontent.com/224501/37055104-1d6bb8e6-2181-11e8-9f4f-c4df5190878d.png)

What do you think?

**Comment by ptrkcsk** [comment] 2018-03-07 07:35
WordPress [sizes](https://github.com/WordPress/WordPress/blob/4.9.4/wp-admin/css/admin-menu.css#L357) the icons. This plugin just provides the SVG and assumes (naively, apparently) that WordPress will style it appropriately.

I think the problem is that WordPress isn't applying the same padding to SVGs as it [does to Dashicons](https://github.com/WordPress/WordPress/blob/4.9.4/wp-admin/css/admin-menu.css#L363).

Anyway, I agree that the smaller height looks much better. I'll look into it!

**Comment by tdwesten** [comment] 2018-03-07 07:37
I think we need to add a extra specific class to the item with a FA icon to scale them down.

**Comment by ptrkcsk** [comment] 2018-03-07 07:51
Yeah, I just noticed that WordPress [recommends](https://codex.wordpress.org/Function_Reference/register_post_type#menu_icon) adding `height="20px" width="20px"` to the SVG element itself, which is a super easy fix. Unfortunately, I just tried it and it had no effect on the icon size.

Adding CSS will be a little bit more involved, but should be doable.

**Comment by ptrkcsk** [comment] 2018-03-20 23:21
Fixed in 81d1203.

**Closed by ptrkcsk** 2018-03-20 23:21 UTC
Labels: enhancement
